name: e_commerce_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'



# ------------------ packages ---------------- #
dependencies:
  flutter:
    sdk: flutter


# utility packages
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  smooth_page_indicator: ^1.1.0

# icon packages
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
# state management
  get: ^4.6.6
  get_storage: ^2.1.1
# product specific
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
# ---------------- packages end -------------- #


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # ---------------- local assets -------------- #
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/brands/
    - assets/images/user/
    - assets/images/payment_methods/
    - assets/images/promo_banners/

  # ---------------- local fonts -------------- #
  fonts:
    - family: Poppins
      fonts:
         - asset:  assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/Poppins-Italic.ttf
           style: italic
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 800